
VN = [
    North = [
        {
            raw: 'Hà Nội',
            code: 'HAN',
            A: [5],
            B: [5],
            C: [5],
            D: [5],
            E: [4],
            sld_src: 'hanoi',
        },
        {
            raw: 'Sa Pa',
            code: 'SP',
            A: [5],
            B: [5],
            C: [5],
            D: [2, 3],
            E: [2],
            sld_src: 'sapa',
        },
        {
            raw: 'Ninh Bình',
            code: 'NB',
            A: [5],
            B: [5],
            C: [5],
            D: [1, 2],
            E: [2, 3],
            sld_src: 'ninhbinh',
        },
        {
            raw: 'Yên Tử',
            code: 'YT',
            A: [1, 3, 4],
            B: [5],
            C: [5],
            D: [1, 2],
            E: [2],
            sld_src: 'yentu',
        },
        {
            raw: 'Mù Cang Chải',
            code: 'MCC',
            A: [5],
            B: [1],
            C: [5],
            D: [2, 3],
            E: [2],
            sld_src: 'mucangchai',
        },
        {
            raw: 'Ba Vì',
            code: 'BV',
            A: [3, 4],
            B: [5],
            C: [5],
            D: [5],
            E: [2],
            sld_src: 'bavi',
        },
        {
            raw: 'Tam Đảo',
            code: 'TD',
            A: [2, 3, 4],
            B: [5],
            C: [5],
            D: [1, 2, 3],
            E: [3],
            sld_src: 'tamdao',
        },
        {
            raw: 'Mai Châu',
            code: 'SQH',
            A: [2, 3, 4],
            B: [1],
            C: [5],
            D: [2, 3],
            E: [2],
            sld_src: 'maichau',
            }
    ],
    Mid = [
        {
            raw: 'Huế',
            code: 'HUI',
            A: [5],
            B: [5],
            C: [5],
            D: [5],
            E: [4],
            sld_src: 'hue',
        },
        {
            raw:'Đà Nẵng',
            code: 'DAN',
            A: [2, 3, 4],
            B: [5],
            C: [5],
            D: [5],
            E: [1],
            sld_src: 'danang'
        },
        {
            raw: 'Hội An',
            code: 'VCL',
            A: [5],
            B: [5],
            C: [5],
            D: [1, 2],
            E: [4],
            sld_src: 'hoian',
        },
        {
            raw: 'Sầm Sơn',
            code: 'THD',
            A: [2, 3, 4],
            B: [5],
            C: [5],
            D: [5],
            E: [1],
            sld_src: 'samson',
        },
        {
            raw: 'Quảng Bình',
            code: 'VDH',
            A: [3, 4],
            B: [2],
            C: [5],
            D: [1, 2],
            E: [1],
            sld_src:'quangbinh',
        },
    ],
    South = [
        {
            raw: 'Hồ Chí Minh',
            code: 'SGN',
            A: [5],
            B: [5],
            C: [5],
            D: [5],
            E: [4],
            sld_src: 'hochiminh'
        },
        {
            raw: 'Nha Trang',
            code: 'CXR',
            A: [5],
            B: [5],
            C: [5],
            D: [5],
            E: [1],
            sld_src: 'nhatrang',
        },
        {
            raw: 'Phú Quốc',
            code: 'PQC',
            A: [2, 3],
            B: [5],
            C: [5],
            D: [5],
            E: [1],
            sld_src: 'phuquoc',
        },
        {
            raw: 'Cà Mau',
            code: 'CAH',
            A: [3, 4],
            B: [2],
            C: [5],
            D: [1, 2],
            E: [3],
            sld_src: 'camau',
        },
        {
            raw: 'Cần Thơ',
            code: 'VCA',
            A: [5],
            B: [5],
            C: [5],
            D: [1, 2, 3],
            E: [4],
            sld_src: 'cantho'
        },
    ]
    
]